LET'S TRY

In [69]:
import numpy as np
import matplotlib.pyplot as plt
import fireworks.ic as fic
import pytest
from numpy.random import seed

In [70]:
seed(42)
N    = 4
mass = 1
p    = [1,0,0], [-1,0,0],[0,1,0],[0,-1,0]
pos  = np.array(p)
v    = [0,0,0], [0,0,0],[0,0,0],[0,0,0]
vel  = np.array(v)
#pos  = np.random.normal(size=3*N).reshape(N,3) # Generate 3xN 1D array and then reshape as a Nx3 array
#vel  = np.random.normal(size=3*N).reshape(N,3) # Generate 3xN 1D array and then reshape as a Nx3 array
mass = np.ones(N)*mass

print ('pos=', pos)
print('vel=', vel)
print('mass=', mass)


pos= [[ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]]
vel= [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
mass= [1. 1. 1. 1.]


In [71]:
#x

ax = pos[:,0]
bx = ax.reshape((N,1))
print(ax.shape)
print(ax)
print(bx.shape)
print(bx)

cx = ax - bx
print(cx)

#y

ay = pos[:,1]
by = ay.reshape((N,1))
#print(ay.shape)
#print(ay)
#print(by.shape)
#print(by)

cy = ay - by
#print(cy)

#y

az = pos[:,2]
bz = az.reshape((N,1))
#print(az.shape)
#print(az)
#print(bz.shape)
#print(bz)

cz = az - bz
#print(cz)

;

(4,)
[ 1 -1  0  0]
(4, 1)
[[ 1]
 [-1]
 [ 0]
 [ 0]]
[[ 0 -2 -1 -1]
 [ 2  0  1  1]
 [ 1 -1  0  0]
 [ 1 -1  0  0]]


''

In [72]:
r = np.array((cx, cy, cz))
print(r.shape)
print(r)

#QUESTO NON FUNZIONA
#r3 = np.linalg.norm(r)
#print(r3)

(3, 4, 4)
[[[ 0 -2 -1 -1]
  [ 2  0  1  1]
  [ 1 -1  0  0]
  [ 1 -1  0  0]]

 [[ 0  0  1 -1]
  [ 0  0  1 -1]
  [-1 -1  0 -2]
  [ 1  1  2  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


In [73]:

deltax2 = r[0,:,:]**2
deltay2 = r[1,:,:]**2
deltaz2 = r[2,:,:]**2
#modr  = np.dot(r, r2)
#print(deltax2.shape)
#print(deltax2)
normr  = deltax2 + deltay2 + deltaz2
normr3 = normr**3
print(normr.shape)
print(normr)
#print(normr3)

(4, 4)
[[0 4 2 2]
 [4 0 2 2]
 [2 2 0 4]
 [2 2 4 0]]


In [74]:
factor = r / normr3
print(factor)

[[[     nan -0.03125 -0.125   -0.125  ]
  [ 0.03125      nan  0.125    0.125  ]
  [ 0.125   -0.125        nan  0.     ]
  [ 0.125   -0.125    0.           nan]]

 [[     nan  0.       0.125   -0.125  ]
  [ 0.           nan  0.125   -0.125  ]
  [-0.125   -0.125        nan -0.03125]
  [ 0.125    0.125    0.03125      nan]]

 [[     nan  0.       0.       0.     ]
  [ 0.           nan  0.       0.     ]
  [ 0.       0.           nan  0.     ]
  [ 0.       0.       0.           nan]]]


/tmp/ipykernel_419/2144248910.py:1: RuntimeWarning: invalid value encountered in divide
  factor = r / normr3


In [75]:
addend = mass*factor
addend[np.isnan(addend)] = 0
print(addend)

[[[ 0.      -0.03125 -0.125   -0.125  ]
  [ 0.03125  0.       0.125    0.125  ]
  [ 0.125   -0.125    0.       0.     ]
  [ 0.125   -0.125    0.       0.     ]]

 [[ 0.       0.       0.125   -0.125  ]
  [ 0.       0.       0.125   -0.125  ]
  [-0.125   -0.125    0.      -0.03125]
  [ 0.125    0.125    0.03125  0.     ]]

 [[ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]]


In [76]:
#addendx = np.triu(addend[0,:,:],1)
#addendy = np.triu(addend[1,:,:],1)
#addendz = np.triu(addend[2,:,:],1)
#print(addendx)
#print(addendy)
#print(addendz)

#NON FUNZIONA PERCHÈ NON BISOGNA FARE SOLO LA UPPER DIAG!

In [77]:
addendx = addend[0,:,:]
addendy = addend[1,:,:]
addendz = addend[2,:,:]
print(addendx)
print(addendy)
print(addendz)

[[ 0.      -0.03125 -0.125   -0.125  ]
 [ 0.03125  0.       0.125    0.125  ]
 [ 0.125   -0.125    0.       0.     ]
 [ 0.125   -0.125    0.       0.     ]]
[[ 0.       0.       0.125   -0.125  ]
 [ 0.       0.       0.125   -0.125  ]
 [-0.125   -0.125    0.      -0.03125]
 [ 0.125    0.125    0.03125  0.     ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
ax = addendx.sum(axis=1)
ay = addendy.sum(axis=1)
az = addendz.sum(axis=1)
print(ax)
print(ay)
print(az)

[-0.28125  0.28125  0.       0.     ]
[ 0.       0.      -0.28125  0.28125]
[0. 0. 0. 0.]


In [82]:
a = np.array((ax, ay, az))
print(a)

[[-0.28125  0.28125  0.       0.     ]
 [ 0.       0.      -0.28125  0.28125]
 [ 0.       0.       0.       0.     ]]


In [79]:
prova = r[:,0,1]
print(prova)
print(cx[0,1],cy[0,1],cz[0,1])
print((np.linalg.norm(prova))**3.)

[-2  0  0]
-2 0 0
8.0


In [80]:
a = [1,2,3,4]
a = np.array(a).reshape((4,1))
print(a.shape)
print(a.T)
b = [1,2,3,4]
b = np.array(b)
print(b.shape)
print(b)

c = a - b

print(c)

(4, 1)
[[1 2 3 4]]
(4,)
[1 2 3 4]
[[ 0 -1 -2 -3]
 [ 1  0 -1 -2]
 [ 2  1  0 -1]
 [ 3  2  1  0]]
