LET'S TRY

In [107]:
import numpy as np
import matplotlib.pyplot as plt
import fireworks.ic as fic
import pytest
from numpy.random import seed

In [108]:
seed(42)
N    = 4
mass = 1
p    = [1,0,0], [-1,0,0],[0,1,0],[0,-1,0]
pos  = np.array(p)
v    = [0,0,0], [0,0,0],[0,0,0],[0,0,0]
vel  = np.array(v)
#pos  = np.random.normal(size=3*N).reshape(N,3) # Generate 3xN 1D array and then reshape as a Nx3 array
#vel  = np.random.normal(size=3*N).reshape(N,3) # Generate 3xN 1D array and then reshape as a Nx3 array
mass = np.ones(N)*mass

print ('pos=', pos)
print('vel=', vel)
print('mass=', mass)


pos= [[ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]]
vel= [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
mass= [1. 1. 1. 1.]


In [109]:
#x

ax = pos[:,0]
bx = ax.reshape((N,1))
print(ax.shape)
print(ax)
print(bx.shape)
print(bx)

cx = bx - ax
print(cx)

#y

ay = pos[:,1]
by = ay.reshape((N,1))
#print(ay.shape)
#print(ay)
#print(by.shape)
#print(by)

cy = by - ay
#print(cy)

#y

az = pos[:,2]
bz = az.reshape((N,1))
#print(az.shape)
#print(az)
#print(bz.shape)
#print(bz)

cz = bz - az
#print(cz)

;

(4,)
[ 1 -1  0  0]
(4, 1)
[[ 1]
 [-1]
 [ 0]
 [ 0]]
[[ 0  2  1  1]
 [-2  0 -1 -1]
 [-1  1  0  0]
 [-1  1  0  0]]


''

In [110]:
r = np.array((cx, cy, cz))
print(r.shape)
print(r)


#r3 = np.linalg.norm(r)
#print(r3)
#QUESTO NON FUNZIONA

(3, 4, 4)
[[[ 0  2  1  1]
  [-2  0 -1 -1]
  [-1  1  0  0]
  [-1  1  0  0]]

 [[ 0  0 -1  1]
  [ 0  0 -1  1]
  [ 1  1  0  2]
  [-1 -1 -2  0]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


In [111]:

deltax2 = r[0,:,:]**2
deltay2 = r[1,:,:]**2
deltaz2 = r[2,:,:]**2
#modr  = np.dot(r, r2)
#print(deltax2.shape)
#print(deltax2)
normr  = np.sqrt(deltax2 + deltay2 + deltaz2 )
normr3 = normr**3
print(normr.shape)
print(normr)
print(normr3)

(4, 4)
[[0.         2.         1.41421356 1.41421356]
 [2.         0.         1.41421356 1.41421356]
 [1.41421356 1.41421356 0.         2.        ]
 [1.41421356 1.41421356 2.         0.        ]]
[[0.         8.         2.82842712 2.82842712]
 [8.         0.         2.82842712 2.82842712]
 [2.82842712 2.82842712 0.         8.        ]
 [2.82842712 2.82842712 8.         0.        ]]


In [112]:
factor = r / normr3
print(factor)

[[[        nan  0.25        0.35355339  0.35355339]
  [-0.25               nan -0.35355339 -0.35355339]
  [-0.35355339  0.35355339         nan  0.        ]
  [-0.35355339  0.35355339  0.                 nan]]

 [[        nan  0.         -0.35355339  0.35355339]
  [ 0.                 nan -0.35355339  0.35355339]
  [ 0.35355339  0.35355339         nan  0.25      ]
  [-0.35355339 -0.35355339 -0.25               nan]]

 [[        nan  0.          0.          0.        ]
  [ 0.                 nan  0.          0.        ]
  [ 0.          0.                 nan  0.        ]
  [ 0.          0.          0.                 nan]]]


/tmp/ipykernel_419/2144248910.py:1: RuntimeWarning: invalid value encountered in divide
  factor = r / normr3


In [113]:
addend = mass*factor
addend[np.isnan(addend)] = 0
print(addend)

[[[ 0.          0.25        0.35355339  0.35355339]
  [-0.25        0.         -0.35355339 -0.35355339]
  [-0.35355339  0.35355339  0.          0.        ]
  [-0.35355339  0.35355339  0.          0.        ]]

 [[ 0.          0.         -0.35355339  0.35355339]
  [ 0.          0.         -0.35355339  0.35355339]
  [ 0.35355339  0.35355339  0.          0.25      ]
  [-0.35355339 -0.35355339 -0.25        0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]


In [114]:
#addendx = np.triu(addend[0,:,:],1)
#addendy = np.triu(addend[1,:,:],1)
#addendz = np.triu(addend[2,:,:],1)
#print(addendx)
#print(addendy)
#print(addendz)

#NON FUNZIONA PERCHÈ NON BISOGNA FARE SOLO LA UPPER DIAG!

In [115]:
addendx = addend[0,:,:]
addendy = addend[1,:,:]
addendz = addend[2,:,:]
print(addendx)
print(addendy)
print(addendz)

[[ 0.          0.25        0.35355339  0.35355339]
 [-0.25        0.         -0.35355339 -0.35355339]
 [-0.35355339  0.35355339  0.          0.        ]
 [-0.35355339  0.35355339  0.          0.        ]]
[[ 0.          0.         -0.35355339  0.35355339]
 [ 0.          0.         -0.35355339  0.35355339]
 [ 0.35355339  0.35355339  0.          0.25      ]
 [-0.35355339 -0.35355339 -0.25        0.        ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [116]:
ax = - addendx.sum(axis=1)
ay = - addendy.sum(axis=1)
az = - addendz.sum(axis=1)
print(ax)
print(ay)
print(az)

[-0.95710678  0.95710678 -0.         -0.        ]
[-0.         -0.         -0.95710678  0.95710678]
[-0. -0. -0. -0.]


In [119]:
acc = np.array((ax, ay, az))
acc = acc.T
print(acc)

[[-0.95710678 -0.         -0.        ]
 [ 0.95710678 -0.         -0.        ]
 [-0.         -0.95710678 -0.        ]
 [-0.          0.95710678 -0.        ]]


In [118]:
acc2     = np.zeros((N,3),float)
force2   = np.zeros((N, 3),float)

for i in range(N):
    for j in range(N):
        if i != j:
            denom      = np.linalg.norm(pos[i] - pos[j])**3
            temp       = - mass[j]*(pos[i] - pos[j]) / denom
            acc2[i,:]   = acc2[i,:] + temp


    force2[i,:]    = Force(mass[i], acc2[i,:])

print(acc2)

[[-0.95710678  0.          0.        ]
 [ 0.95710678  0.          0.        ]
 [ 0.         -0.95710678  0.        ]
 [ 0.          0.95710678  0.        ]]
